--1- WRITE A QUERY TO PRINT TOP 5 CITIES WITH HIGHEST SPENDS AND THEIR PERCENTAGE CONTRIBUTION OF TOTAL CREDIT CARD SPENDS

WITH CITY_SPENDINGS AS (
SELECT CITY, SUM(CAST(amount AS BIGINT)) AS SPENDS, B.TOTAL_SPENDS FROM CCT,
	(SELECT SUM(CAST(amount as BIGINT)) AS TOTAL_SPENDS FROM CCT) B
	GROUP BY CITY, B.TOTAL_SPENDS)
SELECT TOP 5 CITY, SPENDS, ROUND((SPENDS*100.0)/(TOTAL_SPENDS),2) AS CONTRIBUTION_PERCENT FROM CITY_SPENDINGS
	ORDER BY SPENDS DESC;


--2- WRITE A QUERY TO PRINT HIGHEST SPEND MONTH AND AMOUNT SPENT IN THAT MONTH FOR EACH CARD TYPE

SELECT 
	TOP 1
	DATENAME(MONTH,transaction_date) AS SPEND_MONTH, 
	SUM(amount) AS AMOUNT_SPENT, 
	card_type AS CARD_TYPE 
	FROM CCT
	GROUP BY DATENAME(MONTH,transaction_date), card_type
	ORDER BY SUM(amount) DESC;


WITH 
CARD_GROUPS AS (
SELECT 
	YEAR(transaction_date) AS SPENT_YEAR, 
	DATENAME(MONTH,transaction_date) AS SPENT_MONTH, 
	SUM(amount) AS TOTAL_SPENT, 
	CARD_TYPE from CCT
GROUP BY YEAR(transaction_date), DATENAME(MONTH,transaction_date), card_type
),

CARD_GRP_RNK AS (
SELECT *, 
RANK() OVER(PARTITION BY CARD_TYPE ORDER BY TOTAL_SPENT DESC) AS RNK
FROM CARD_GROUPS)

SELECT CARD_TYPE, SPENT_YEAR, SPENT_MONTH, TOTAL_SPENT FROM CARD_GRP_RNK WHERE RNK = 1;



--3- WRITE A QUERY TO PRINT THE TRANSACTION DETAILS(ALL COLUMNS FROM THE TABLE) FOR EACH CARD TYPE WHEN
--IT REACHES A CUMULATIVE OF 1000000 TOTAL SPENDS(WE SHOULD HAVE 4 ROWS IN THE O/P ONE FOR EACH CARD TYPE)

WITH CUM_SUM_TAB AS (
SELECT *, 
	SUM(CAST(amount AS bigint)) OVER(PARTITION BY card_type ORDER BY transaction_date rows unbounded preceding) AS CUM_SUM 
	FROM CCT
),

CUM_SUM_RNK AS (
SELECT *, 
	RANK() OVER(PARTITION BY CARD_TYPE ORDER BY CUM_SUM) AS RNK 
	FROM CUM_SUM_TAB 
	WHERE CUM_SUM >= 1000000)
	
SELECT * FROM CUM_SUM_RNK WHERE RNK = 1;


--4- WRITE A QUERY TO FIND CITY WHICH HAD LOWEST PERCENTAGE SPEND FOR GOLD CARD TYPE

--SOLUTION 1:
WITH CARD_PART AS (
SELECT 
	CITY, CARD_TYPE, 
	SUM(AMOUNT) AS TOTAL_SPENT 
	FROM CCT 
	GROUP BY CITY, CARD_TYPE
),

CARD_PART_RANK AS (
SELECT *, 
	RANK() OVER(PARTITION BY CARD_TYPE ORDER BY TOTAL_SPENT ASC) AS RNK
	FROM CARD_PART)

SELECT CARD_TYPE, CITY, TOTAL_SPENT FROM CARD_PART_RANK WHERE CARD_TYPE = 'Gold' AND RNK = 1;

--SOLUTION 2:

WITH GOLD_AMT AS (
SELECT CITY, AMOUNT, 
	SUM(AMOUNT) OVER(PARTITION BY CARD_TYPE) AS TOTAL_AMOUNT 
	FROM CCT WHERE CARD_TYPE = 'Gold'),

GOLD_PERC AS(
SELECT CITY, 
	(SUM(AMOUNT)*1.0)/TOTAL_AMOUNT AS SPENT_PERC
	FROM GOLD_AMT AMT
	GROUP BY CITY, TOTAL_AMOUNT)

SELECT TOP 1 * FROM GOLD_PERC ORDER BY SPENT_PERC ASC;


--5- WRITE A QUERY TO PRINT 3 COLUMNS:  CITY, HIGHEST_EXPENSE_TYPE , LOWEST_EXPENSE_TYPE (EXAMPLE FORMAT : DELHI , BILLS, FUEL)

-- SOLUTION 1:
WITH EXP_SPENDS AS (
SELECT 
	CITY, EXP_TYPE, SUM(AMOUNT) AS TOTAL_SPENT
	FROM CCT GROUP BY CITY, EXP_TYPE
),

EXP_SPENDS_HL AS (
SELECT CITY, EXP_TYPE, TOTAL_SPENT,
	MIN(TOTAL_SPENT) OVER(PARTITION BY CITY) AS MIN_SPENT,
	MAX(TOTAL_SPENT) OVER(PARTITION BY CITY) AS MAX_SPENT
	FROM EXP_SPENDS
)

SELECT CITY,
	MAX(CASE WHEN TOTAL_SPENT = MIN_SPENT THEN EXP_TYPE END) AS LOW_EXPENSE_TYPE,
	MAX(CASE WHEN TOTAL_SPENT = MAX_SPENT THEN EXP_TYPE END) AS HIGH_EXPENSE_TYPE
	FROM EXP_SPENDS_HL
	GROUP BY CITY;

-- SOLUTION 2:
WITH EXP_SPENDS AS (
SELECT 
	CITY, EXP_TYPE, SUM(AMOUNT) AS TOTAL_SPENT
	FROM CCT GROUP BY CITY, EXP_TYPE
),

EXP_SPENDS_HL AS (
SELECT CITY, 
	--RANK() OVER(PARTITION BY CITY ORDER BY TOTAL_SPENT) AS EXP_RANK 
	FIRST_VALUE(EXP_TYPE) OVER(PARTITION BY CITY ORDER BY TOTAL_SPENT ASC) AS LOW_EXPENSE_TYPE,
	FIRST_VALUE(EXP_TYPE) OVER(PARTITION BY CITY ORDER BY TOTAL_SPENT DESC) AS HIGH_EXPENSE_TYPE
	FROM EXP_SPENDS
)

SELECT DISTINCT * FROM EXP_SPENDS_HL;


--6- WRITE A QUERY TO FIND PERCENTAGE CONTRIBUTION OF SPENDS BY FEMALES FOR EACH EXPENSE TYPE

WITH FEMALE_SPENDS AS(
	SELECT A.EXP_TYPE, A.AMT_SPENT_FEM, B.TOTAL_AMOUNT FROM (
	(SELECT EXP_TYPE, SUM(AMOUNT) AS AMT_SPENT_FEM FROM CCT WHERE GENDER = 'F' GROUP BY EXP_TYPE) A
	JOIN
	(SELECT EXP_TYPE, SUM(AMOUNT) AS TOTAL_AMOUNT FROM CCT GROUP BY EXP_TYPE) B
	ON A.EXP_TYPE = B.EXP_TYPE)
)

SELECT EXP_TYPE, (AMT_SPENT_FEM*100.0)/TOTAL_AMOUNT AS FEMALE_CONTRIBUTION FROM FEMALE_SPENDS;


--7- WHICH CARD AND EXPENSE TYPE COMBINATION SAW HIGHEST MONTH OVER MONTH GROWTH IN JAN-2014


WITH MONTHLY_SPENDS AS (
SELECT 
	YEAR(TRANSACTION_DATE) AS CURRENT_YEAR, 
	MONTH(TRANSACTION_DATE) AS CURRENT_MONTH,
	CARD_TYPE,
	EXP_TYPE,
	SUM(AMOUNT) AS CURRENT_MONTH_AMT
	FROM CCT
	GROUP BY YEAR(TRANSACTION_DATE), MONTH(TRANSACTION_DATE), CARD_TYPE, EXP_TYPE
),

PREVIOUS_MTH_SPND AS (
SELECT *,
	LAG(CURRENT_MONTH_AMT,1,0) OVER(ORDER BY CURRENT_YEAR, CURRENT_MONTH ASC) AS PREVIOUS_SPENDS,
	CURRENT_MONTH_AMT - (LAG(CURRENT_MONTH_AMT,1,0) OVER(ORDER BY CURRENT_YEAR, CURRENT_MONTH ASC)) AS MOM_GROWTH
	FROM MONTHLY_SPENDS
) 
SELECT TOP 1 * FROM PREVIOUS_MTH_SPND WHERE CURRENT_YEAR = 2014 AND CURRENT_MONTH = 1 ORDER BY MOM_GROWTH DESC;


--8- DURING WEEKENDS WHICH CITY HAS HIGHEST TOTAL SPEND TO TOTAL NO OF TRANSCATIONS RATIO 

WITH WEEKEND_TXNS AS (
SELECT 
	CITY, 
	SUM(AMOUNT) AS WEEKEND_SPEND, 
	COUNT(TRANSACTION_ID) AS TXN_COUNT,
	1.0*(SUM(AMOUNT))/COUNT(TRANSACTION_ID) AS SP_TXN_RATIO
	FROM CCT 
	WHERE DATEPART(WEEKDAY,TRANSACTION_DATE) IN (1,7) 
	GROUP BY CITY 
)
SELECT TOP 1 * FROM WEEKEND_TXNS ORDER BY SP_TXN_RATIO DESC;

-- DURING WEEKDAYS:

WITH WEEKEND_TXNS AS (
SELECT 
	CITY, 
	SUM(AMOUNT) AS WEEKEND_SPEND, 
	COUNT(TRANSACTION_ID) AS TXN_COUNT,
	1.0*(SUM(AMOUNT))/COUNT(TRANSACTION_ID) AS SP_TXN_RATIO
	FROM CCT 
	WHERE DATEPART(WEEKDAY,TRANSACTION_DATE) NOT IN (1,7) 
	GROUP BY CITY 
)
SELECT TOP 1 * FROM WEEKEND_TXNS ORDER BY SP_TXN_RATIO DESC;

--9- WHICH CITY TOOK LEAST NUMBER OF DAYS TO REACH ITS 500TH TRANSACTION AFTER THE FIRST TRANSACTION IN THAT CITY

WITH CITY_TXNS AS (
SELECT 
	CITY, 
	TRANSACTION_DATE,
	ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY TRANSACTION_DATE) AS ROW_NUM
	FROM CCT
),
TXNS_DIFF AS (
SELECT 
	CITY,
	MAX(CASE WHEN ROW_NUM = 1 THEN TRANSACTION_DATE END) AS TXN_1,
	MAX(CASE WHEN ROW_NUM = 500 THEN TRANSACTION_DATE END) AS TXN_500
	FROM CITY_TXNS
	GROUP BY CITY
)
SELECT TOP 1
	CITY,
	DATEDIFF(DAY,TXN_1,TXN_500) AS NO_OF_DAYS
	FROM TXNS_DIFF
	WHERE TXN_500 IS NOT NULL
	ORDER BY DATEDIFF(DAY,TXN_1,TXN_500) ASC;